/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface) {
    await queryInterface.bulkInsert('Candidates', [{
      name: 'Aртём Васильев',
      email: 'Vasilyev@yandex.ru',
      experience: 8.5,
      photo: 'https://avatars.mds.yandex.net/i?id=735b30e1e137aa2b6c4675dd12ce25e48598b6d8-7543946-images-thumbs&n=13',
      phone: '8(906)2541465',
      skype: 'ArtemVasilyev',
      zoom: 'ArtemVasilyev',
      status: 'Work',
      date: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Татьяна Шматченко',
      email: 'Tanya@gmail.com',
      experience: 6.4,
      photo: 'https://avatars.mds.yandex.net/i?id=b2aaafc5f7fc5375765278b6fd51f91d861fa10c-8312020-images-thumbs&n=13',
      phone: '8(905)8819245',
      skype: 'TatyanaShmatchenko',
      zoom: 'TatyanaShmatchenko',
      status: 'VideoCall',
      date: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Айгуль Кантюкова',
      email: 'Kantykova@yahoo.com',
      experience: 5.2,
      photo: 'https://avatars.mds.yandex.net/i?id=adc4bc598f1938ca4d9b226296b3bcb2037cf1b9-7546007-images-thumbs&n=13',
      phone: '8(916)7564598',
      skype: 'JuliaKantykova',
      zoom: 'JuliaKantykova',
      status: 'Offer',
      date: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Ирина Архипова',
      email: 'Arhipova@mail.ru',
      experience: 2.7,
      photo: 'https://avatars.mds.yandex.net/i?id=11f7104683a17e9b28881aee3b154233af791530-8257511-images-thumbs&n=13',
      phone: '8(903)7424545',
      skype: 'IrinaArhipova',
      zoom: 'IrinaArhipova',
      status: 'Interview',
      date: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Павел Заболотников',
      email: 'Zabolotnikov@mail.ru',
      experience: 3.2,
      photo: 'https://avatars.mds.yandex.net/i?id=be804aafa6ddfadb8d042357d6f9847d0feade61-8495831-images-thumbs&n=13',
      phone: '8(907)4664514',
      skype: 'PavelZabolotnikov',
      zoom: 'PavelZabolotnikov',
      status: 'Call',
      date: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    }], {});
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete('Candidates');
  },
};
